/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessagePublic {
  'id' : MessageId,
  'content' : string,
  'ride_id' : RideId,
  'sender_id' : string,
  'timestamp' : Timestamp,
}
export type CreateRideResult = { 'ok' : RidePublic } |
  { 'err' : string };
export type GenderPreference = { 'female' : null } |
  { 'male' : null } |
  { 'none' : null };
export type JoinResult = { 'ok' : RidePublic } |
  { 'err' : string };
export type MessageId = bigint;
export type RideId = bigint;
export interface RidePublic {
  'id' : RideId,
  'joined_users' : Array<string>,
  'destination' : string,
  'creator_id' : string,
  'creator_gender' : GenderPreference,
  'seats_total' : bigint,
  'total_fare' : bigint,
  'seats_filled' : bigint,
  'datetime' : Timestamp,
}
export type SaveMessageResult = { 'ok' : ChatMessagePublic } |
  { 'notMember' : null } |
  { 'rideNotFound' : null };
export type Timestamp = bigint;
export interface UserProfilePublic {
  'id' : string,
  'name' : string,
  'hasPhoto' : boolean,
  'email' : string,
  'gender' : GenderPreference,
}
export type WithdrawResult = { 'ok' : null } |
  { 'notJoined' : null } |
  { 'rideNotFound' : null };
export interface _SERVICE {
  'createRide' : ActorMethod<
    [string, Timestamp, bigint, bigint],
    CreateRideResult
  >,
  'getGenderFilteredRides' : ActorMethod<
    [[] | [GenderPreference]],
    Array<RidePublic>
  >,
  'getJoinedRides' : ActorMethod<[], Array<RidePublic>>,
  'getMessages' : ActorMethod<[RideId], Array<ChatMessagePublic>>,
  'getMyRides' : ActorMethod<[], Array<RidePublic>>,
  'getPostedRides' : ActorMethod<[], Array<RidePublic>>,
  'getProfile' : ActorMethod<[], [] | [UserProfilePublic]>,
  'getProfilePhoto' : ActorMethod<
    [string],
    [] | [{ 'data' : Uint8Array, 'mime' : string }]
  >,
  'getRideDetails' : ActorMethod<[RideId], [] | [RidePublic]>,
  'getRides' : ActorMethod<[], Array<RidePublic>>,
  'joinRide' : ActorMethod<[RideId], JoinResult>,
  'saveMessage' : ActorMethod<[RideId, string], SaveMessageResult>,
  'setProfile' : ActorMethod<
    [string, string, GenderPreference],
    UserProfilePublic
  >,
  'setProfilePhoto' : ActorMethod<[Uint8Array, string], undefined>,
  'withdrawRide' : ActorMethod<[RideId], WithdrawResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];