/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const RideId = IDL.Nat;
export const GenderPreference = IDL.Variant({
  'female' : IDL.Null,
  'male' : IDL.Null,
  'none' : IDL.Null,
});
export const RidePublic = IDL.Record({
  'id' : RideId,
  'joined_users' : IDL.Vec(IDL.Text),
  'destination' : IDL.Text,
  'creator_id' : IDL.Text,
  'creator_gender' : GenderPreference,
  'seats_total' : IDL.Nat,
  'total_fare' : IDL.Nat,
  'seats_filled' : IDL.Nat,
  'datetime' : Timestamp,
});
export const CreateRideResult = IDL.Variant({
  'ok' : RidePublic,
  'err' : IDL.Text,
});
export const MessageId = IDL.Nat;
export const ChatMessagePublic = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'ride_id' : RideId,
  'sender_id' : IDL.Text,
  'timestamp' : Timestamp,
});
export const UserProfilePublic = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'hasPhoto' : IDL.Bool,
  'email' : IDL.Text,
  'gender' : GenderPreference,
});
export const JoinResult = IDL.Variant({ 'ok' : RidePublic, 'err' : IDL.Text });
export const SaveMessageResult = IDL.Variant({
  'ok' : ChatMessagePublic,
  'notMember' : IDL.Null,
  'rideNotFound' : IDL.Null,
});
export const WithdrawResult = IDL.Variant({
  'ok' : IDL.Null,
  'notJoined' : IDL.Null,
  'rideNotFound' : IDL.Null,
});

export const idlService = IDL.Service({
  'createRide' : IDL.Func(
      [IDL.Text, Timestamp, IDL.Nat, IDL.Nat],
      [CreateRideResult],
      [],
    ),
  'getGenderFilteredRides' : IDL.Func(
      [IDL.Opt(GenderPreference)],
      [IDL.Vec(RidePublic)],
      ['query'],
    ),
  'getJoinedRides' : IDL.Func([], [IDL.Vec(RidePublic)], ['query']),
  'getMessages' : IDL.Func([RideId], [IDL.Vec(ChatMessagePublic)], ['query']),
  'getMyRides' : IDL.Func([], [IDL.Vec(RidePublic)], ['query']),
  'getPostedRides' : IDL.Func([], [IDL.Vec(RidePublic)], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], ['query']),
  'getProfilePhoto' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Record({ 'data' : IDL.Vec(IDL.Nat8), 'mime' : IDL.Text }))],
      ['query'],
    ),
  'getRideDetails' : IDL.Func([RideId], [IDL.Opt(RidePublic)], ['query']),
  'getRides' : IDL.Func([], [IDL.Vec(RidePublic)], ['query']),
  'joinRide' : IDL.Func([RideId], [JoinResult], []),
  'saveMessage' : IDL.Func([RideId, IDL.Text], [SaveMessageResult], []),
  'setProfile' : IDL.Func(
      [IDL.Text, IDL.Text, GenderPreference],
      [UserProfilePublic],
      [],
    ),
  'setProfilePhoto' : IDL.Func([IDL.Vec(IDL.Nat8), IDL.Text], [], []),
  'withdrawRide' : IDL.Func([RideId], [WithdrawResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const RideId = IDL.Nat;
  const GenderPreference = IDL.Variant({
    'female' : IDL.Null,
    'male' : IDL.Null,
    'none' : IDL.Null,
  });
  const RidePublic = IDL.Record({
    'id' : RideId,
    'joined_users' : IDL.Vec(IDL.Text),
    'destination' : IDL.Text,
    'creator_id' : IDL.Text,
    'creator_gender' : GenderPreference,
    'seats_total' : IDL.Nat,
    'total_fare' : IDL.Nat,
    'seats_filled' : IDL.Nat,
    'datetime' : Timestamp,
  });
  const CreateRideResult = IDL.Variant({ 'ok' : RidePublic, 'err' : IDL.Text });
  const MessageId = IDL.Nat;
  const ChatMessagePublic = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'ride_id' : RideId,
    'sender_id' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const UserProfilePublic = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'hasPhoto' : IDL.Bool,
    'email' : IDL.Text,
    'gender' : GenderPreference,
  });
  const JoinResult = IDL.Variant({ 'ok' : RidePublic, 'err' : IDL.Text });
  const SaveMessageResult = IDL.Variant({
    'ok' : ChatMessagePublic,
    'notMember' : IDL.Null,
    'rideNotFound' : IDL.Null,
  });
  const WithdrawResult = IDL.Variant({
    'ok' : IDL.Null,
    'notJoined' : IDL.Null,
    'rideNotFound' : IDL.Null,
  });
  
  return IDL.Service({
    'createRide' : IDL.Func(
        [IDL.Text, Timestamp, IDL.Nat, IDL.Nat],
        [CreateRideResult],
        [],
      ),
    'getGenderFilteredRides' : IDL.Func(
        [IDL.Opt(GenderPreference)],
        [IDL.Vec(RidePublic)],
        ['query'],
      ),
    'getJoinedRides' : IDL.Func([], [IDL.Vec(RidePublic)], ['query']),
    'getMessages' : IDL.Func([RideId], [IDL.Vec(ChatMessagePublic)], ['query']),
    'getMyRides' : IDL.Func([], [IDL.Vec(RidePublic)], ['query']),
    'getPostedRides' : IDL.Func([], [IDL.Vec(RidePublic)], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], ['query']),
    'getProfilePhoto' : IDL.Func(
        [IDL.Text],
        [
          IDL.Opt(
            IDL.Record({ 'data' : IDL.Vec(IDL.Nat8), 'mime' : IDL.Text })
          ),
        ],
        ['query'],
      ),
    'getRideDetails' : IDL.Func([RideId], [IDL.Opt(RidePublic)], ['query']),
    'getRides' : IDL.Func([], [IDL.Vec(RidePublic)], ['query']),
    'joinRide' : IDL.Func([RideId], [JoinResult], []),
    'saveMessage' : IDL.Func([RideId, IDL.Text], [SaveMessageResult], []),
    'setProfile' : IDL.Func(
        [IDL.Text, IDL.Text, GenderPreference],
        [UserProfilePublic],
        [],
      ),
    'setProfilePhoto' : IDL.Func([IDL.Vec(IDL.Nat8), IDL.Text], [], []),
    'withdrawRide' : IDL.Func([RideId], [WithdrawResult], []),
  });
};

export const init = ({ IDL }) => { return []; };