/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface RidePublic {
    id: RideId;
    joined_users: Array<string>;
    destination: string;
    creator_id: string;
    creator_gender: GenderPreference;
    seats_total: bigint;
    total_fare: bigint;
    seats_filled: bigint;
    datetime: Timestamp;
}
export type CreateRideResult = {
    __kind__: "ok";
    ok: RidePublic;
} | {
    __kind__: "err";
    err: string;
};
export type MessageId = bigint;
export type JoinResult = {
    __kind__: "ok";
    ok: RidePublic;
} | {
    __kind__: "err";
    err: string;
};
export type RideId = bigint;
export type SaveMessageResult = {
    __kind__: "ok";
    ok: ChatMessagePublic;
} | {
    __kind__: "notMember";
    notMember: null;
} | {
    __kind__: "rideNotFound";
    rideNotFound: null;
};
export interface ChatMessagePublic {
    id: MessageId;
    content: string;
    ride_id: RideId;
    sender_id: string;
    timestamp: Timestamp;
}
export interface UserProfilePublic {
    id: string;
    name: string;
    hasPhoto: boolean;
    email: string;
    gender: GenderPreference;
}
export enum GenderPreference {
    female = "female",
    male = "male",
    none = "none"
}
export enum WithdrawResult {
    ok = "ok",
    notJoined = "notJoined",
    rideNotFound = "rideNotFound"
}
export interface backendInterface {
    createRide(destination: string, datetime: Timestamp, total_fare: bigint, seats_total: bigint): Promise<CreateRideResult>;
    getGenderFilteredRides(gender: GenderPreference | null): Promise<Array<RidePublic>>;
    getJoinedRides(): Promise<Array<RidePublic>>;
    getMessages(ride_id: RideId): Promise<Array<ChatMessagePublic>>;
    getMyRides(): Promise<Array<RidePublic>>;
    getPostedRides(): Promise<Array<RidePublic>>;
    getProfile(): Promise<UserProfilePublic | null>;
    getProfilePhoto(userId: string): Promise<{
        data: Uint8Array;
        mime: string;
    } | null>;
    getRideDetails(ride_id: RideId): Promise<RidePublic | null>;
    getRides(): Promise<Array<RidePublic>>;
    joinRide(ride_id: RideId): Promise<JoinResult>;
    saveMessage(ride_id: RideId, content: string): Promise<SaveMessageResult>;
    setProfile(name: string, email: string, gender: GenderPreference): Promise<UserProfilePublic>;
    setProfilePhoto(data: Uint8Array, mime: string): Promise<void>;
    withdrawRide(ride_id: RideId): Promise<WithdrawResult>;
}
import type { ChatMessagePublic as _ChatMessagePublic, CreateRideResult as _CreateRideResult, GenderPreference as _GenderPreference, JoinResult as _JoinResult, RideId as _RideId, RidePublic as _RidePublic, SaveMessageResult as _SaveMessageResult, Timestamp as _Timestamp, UserProfilePublic as _UserProfilePublic, WithdrawResult as _WithdrawResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createRide(arg0: string, arg1: Timestamp, arg2: bigint, arg3: bigint): Promise<CreateRideResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createRide(arg0, arg1, arg2, arg3);
                return from_candid_CreateRideResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRide(arg0, arg1, arg2, arg3);
            return from_candid_CreateRideResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGenderFilteredRides(arg0: GenderPreference | null): Promise<Array<RidePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGenderFilteredRides(to_candid_opt_n7(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGenderFilteredRides(to_candid_opt_n7(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJoinedRides(): Promise<Array<RidePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJoinedRides();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJoinedRides();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessages(arg0: RideId): Promise<Array<ChatMessagePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0);
            return result;
        }
    }
    async getMyRides(): Promise<Array<RidePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRides();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRides();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPostedRides(): Promise<Array<RidePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostedRides();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostedRides();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfilePhoto(arg0: string): Promise<{
        data: Uint8Array;
        mime: string;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfilePhoto(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfilePhoto(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRideDetails(arg0: RideId): Promise<RidePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRideDetails(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRideDetails(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRides(): Promise<Array<RidePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRides();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRides();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async joinRide(arg0: RideId): Promise<JoinResult> {
        if (this.processError) {
            try {
                const result = await this.actor.joinRide(arg0);
                return from_candid_JoinResult_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinRide(arg0);
            return from_candid_JoinResult_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveMessage(arg0: RideId, arg1: string): Promise<SaveMessageResult> {
        if (this.processError) {
            try {
                const result = await this.actor.saveMessage(arg0, arg1);
                return from_candid_SaveMessageResult_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveMessage(arg0, arg1);
            return from_candid_SaveMessageResult_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async setProfile(arg0: string, arg1: string, arg2: GenderPreference): Promise<UserProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.setProfile(arg0, arg1, to_candid_GenderPreference_n8(this._uploadFile, this._downloadFile, arg2));
                return from_candid_UserProfilePublic_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setProfile(arg0, arg1, to_candid_GenderPreference_n8(this._uploadFile, this._downloadFile, arg2));
            return from_candid_UserProfilePublic_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async setProfilePhoto(arg0: Uint8Array, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setProfilePhoto(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setProfilePhoto(arg0, arg1);
            return result;
        }
    }
    async withdrawRide(arg0: RideId): Promise<WithdrawResult> {
        if (this.processError) {
            try {
                const result = await this.actor.withdrawRide(arg0);
                return from_candid_WithdrawResult_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.withdrawRide(arg0);
            return from_candid_WithdrawResult_n19(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_CreateRideResult_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CreateRideResult): CreateRideResult {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_GenderPreference_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GenderPreference): GenderPreference {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_JoinResult_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JoinResult): JoinResult {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_RidePublic_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RidePublic): RidePublic {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_SaveMessageResult_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SaveMessageResult): SaveMessageResult {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfilePublic_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfilePublic): UserProfilePublic {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawResult_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawResult): WithdrawResult {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfilePublic]): UserProfilePublic | null {
    return value.length === 0 ? null : from_candid_UserProfilePublic_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        data: Uint8Array;
        mime: string;
    }]): {
    data: Uint8Array;
    mime: string;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RidePublic]): RidePublic | null {
    return value.length === 0 ? null : from_candid_RidePublic_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    hasPhoto: boolean;
    email: string;
    gender: _GenderPreference;
}): {
    id: string;
    name: string;
    hasPhoto: boolean;
    email: string;
    gender: GenderPreference;
} {
    return {
        id: value.id,
        name: value.name,
        hasPhoto: value.hasPhoto,
        email: value.email,
        gender: from_candid_GenderPreference_n5(_uploadFile, _downloadFile, value.gender)
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RideId;
    joined_users: Array<string>;
    destination: string;
    creator_id: string;
    creator_gender: _GenderPreference;
    seats_total: bigint;
    total_fare: bigint;
    seats_filled: bigint;
    datetime: _Timestamp;
}): {
    id: RideId;
    joined_users: Array<string>;
    destination: string;
    creator_id: string;
    creator_gender: GenderPreference;
    seats_total: bigint;
    total_fare: bigint;
    seats_filled: bigint;
    datetime: Timestamp;
} {
    return {
        id: value.id,
        joined_users: value.joined_users,
        destination: value.destination,
        creator_id: value.creator_id,
        creator_gender: from_candid_GenderPreference_n5(_uploadFile, _downloadFile, value.creator_gender),
        seats_total: value.seats_total,
        total_fare: value.total_fare,
        seats_filled: value.seats_filled,
        datetime: value.datetime
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ChatMessagePublic;
} | {
    notMember: null;
} | {
    rideNotFound: null;
}): {
    __kind__: "ok";
    ok: ChatMessagePublic;
} | {
    __kind__: "notMember";
    notMember: null;
} | {
    __kind__: "rideNotFound";
    rideNotFound: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "notMember" in value ? {
        __kind__: "notMember",
        notMember: value.notMember
    } : "rideNotFound" in value ? {
        __kind__: "rideNotFound",
        rideNotFound: value.rideNotFound
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _RidePublic;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: RidePublic;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_RidePublic_n3(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    notJoined: null;
} | {
    rideNotFound: null;
}): WithdrawResult {
    return "ok" in value ? WithdrawResult.ok : "notJoined" in value ? WithdrawResult.notJoined : "rideNotFound" in value ? WithdrawResult.rideNotFound : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    female: null;
} | {
    male: null;
} | {
    none: null;
}): GenderPreference {
    return "female" in value ? GenderPreference.female : "male" in value ? GenderPreference.male : "none" in value ? GenderPreference.none : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RidePublic>): Array<RidePublic> {
    return value.map((x)=>from_candid_RidePublic_n3(_uploadFile, _downloadFile, x));
}
function to_candid_GenderPreference_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GenderPreference): _GenderPreference {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GenderPreference | null): [] | [_GenderPreference] {
    return value === null ? candid_none() : candid_some(to_candid_GenderPreference_n8(_uploadFile, _downloadFile, value));
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GenderPreference): {
    female: null;
} | {
    male: null;
} | {
    none: null;
} {
    return value == GenderPreference.female ? {
        female: null
    } : value == GenderPreference.male ? {
        male: null
    } : value == GenderPreference.none ? {
        none: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
